set nocompatible
let &rtp  = '~/.vim/bundle/FastFold,' . &rtp
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

let g:vimtex_fold_enabled = 1
" let g:vimtex_fold_commands_default = {}
    " \ 'tikzset' : 'single',
    " \}

" Here we need to edit a large tex file, e.g. a thesis or long paper
edit main.tex

function! Test()
  profile start profile.log
  profile func *level
  FastFoldUpdate!
  profile pause
  noautocmd qall!
endfunction

nnoremap <space>s :call Test()<cr>jk:w

