set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

nnoremap q :qa!<cr>

silent edit main.tex

" Open the toc to inspect the chapter numbers
VimtexTocOpen
