add_cus_dep( 'gloss-glo', 'gloss-gls', 0, 'makegloss' );
add_cus_dep( 'symbols-glo', 'symbols-gls', 0, 'makesymbols' );

sub makegloss {
        system( "makeindex -t \"$_[0].gloss-glg\" -s \"$_[0].ist\" -o \"$_[0].gloss-gls\" \"$_[0].gloss-glo\"" );
}
sub makesymbols {
        system( "makeindex -t \"$_[0].symbols-glg\" -s \"$_[0].ist\" -o \"$_[0].symbols-gls\" \"$_[0].symbols-glo\"" );
}
