set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

let g:vimtex_imaps_disabled = [
      \ 'a',
      \ 'S',
      \]

call vimtex#imaps#add_map({ 'lhs' : 'vv', 'rhs' : '\vec{' })
call vimtex#imaps#add_map({
  \ 'lhs' : 'test',
  \ 'rhs' : 'tested',
  \ 'leader' : '',
  \ 'wrapper' : 'vimtex#imaps#wrap_trivial',
  \})

