set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
filetype plugin indent on
syntax on

let g:tex_flavor = "latex"
set iskeyword+=:
set grepprg=grep\ -nH\ $*
let g:vimtex_latexmk_options ="-pdf -verbose -file-line-error -synctex=1 -interaction=nonstopmode"
let g:vimtex_quickfix_ignore_all_warnings = 0
