push @generated_exts, "glo";
push @generated_exts, "ist";
push @generated_exts, "gloss-glo";
push @generated_exts, "gloss-gls";
push @generated_exts, "gloss-glg";
push @generated_exts, "symbols-glo";
push @generated_exts, "symbols-gls";
push @generated_exts, "symbols-glg";

add_cus_dep( 'gloss-glo', 'gloss-gls', 0, 'makegloss' );
add_cus_dep( 'symbols-glo', 'symbols-gls', 0, 'makesymbols' );

sub makegloss {
        system( "makeindex -t \"$_[0].gloss-glg\" -s \"$_[0].ist\" -o \"$_[0].gloss-gls\" \"$_[0].gloss-glo\"" );
}
sub makesymbols {
        system( "makeindex -t \"$_[0].symbols-glg\" -s \"$_[0].ist\" -o \"$_[0].symbols-gls\" \"$_[0].symbols-glo\"" );
}
