set nocompatible
let &rtp = '../../..,' . &rtp
let &rtp = '~/.vim/bundle/neocomplete,' . &rtp
filetype plugin indent on
syntax enable

set encoding=utf-8
set hidden
set backspace=2

if has('conceal')
  set conceallevel=2 concealcursor=niv
endif

let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_camel_case = 1
let g:neocomplete#enable_auto_delimiter = 1
let g:neocomplete#enable_auto_close_preview = 1

let g:neocomplete#keyword_patterns = {}
let g:neocomplete#sources#omni#input_patterns = {}

let g:neocomplete#keyword_patterns.tex     = '[a-zA-ZæÆøØåÅ][0-9a-zA-ZæÆøØåÅ]\+'
let g:neocomplete#sources#omni#input_patterns.tex =
      \ '\v\\\a*(ref|cite)\a*([^]]*\])?\{([^}]*,)*[^}]*'

silent edit ../../test-completions/main.tex
silent normal! zRgg7jo
startinsert
