test: test1 test2 test3 test4 test5

test1:
	@echo "Starting test 1"
	@nvim -u vimrc_test1
	@echo -e "\n"

test2:
	@echo "Starting test 2"
	@nvim -u vimrc_test2
	@echo -e "\n"

test3:
	@echo "Starting test 3"
	@nvim -u vimrc_test3
	@echo -e "\n"

test4:
	@echo "Starting test 4"
	@nvim -u vimrc_test4
	@echo -e "\n"

test5:
	@echo "Starting test 5"
	@nvim -u vimrc_test5
	@echo -e "\n"
